// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: media.sql

package data

import (
	"context"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (public_media_id, user_id, filename, mime_type, size)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, public_media_id, user_id, filename, mime_type, size, created_at
`

type CreateMediaParams struct {
	PublicMediaID string    `json:"public_media_id"`
	UserID        uuid.UUID `json:"user_id"`
	Filename      string    `json:"filename"`
	MimeType      string    `json:"mime_type"`
	Size          int64     `json:"size"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.PublicMediaID,
		arg.UserID,
		arg.Filename,
		arg.MimeType,
		arg.Size,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.PublicMediaID,
		&i.UserID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, public_media_id, user_id, filename, mime_type, size, created_at FROM media WHERE public_media_id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, publicMediaID string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaByID, publicMediaID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.PublicMediaID,
		&i.UserID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaNameByPublicID = `-- name: GetMediaNameByPublicID :one
SELECT filename FROM media WHERE public_media_id = $1
`

func (q *Queries) GetMediaNameByPublicID(ctx context.Context, publicMediaID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMediaNameByPublicID, publicMediaID)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const listMediaByUser = `-- name: ListMediaByUser :many
SELECT media.id, media.public_media_id, media.user_id, media.filename, media.mime_type, media.size, media.created_at FROM media JOIN users ON media.user_id = users.id
WHERE users.public_id = $1
`

func (q *Queries) ListMediaByUser(ctx context.Context, publicID string) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByUser, publicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.PublicMediaID,
			&i.UserID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
